function agent = addAgent(pos_a , pos_waypoint);
% addAgent - Return a struct with agent details
%
% Syntax: agent = addAgent(name, position, velocity, goal)
%  
agent = [];
for i = 1 : length(pos_a)
    agent = [agent ; struct( 'name', num2str(i), 'position', pos_a(i,:), ...
        'velocity',[0 0], ...
        'goal',pos_waypoint(i,:), ...
        'path',[], ...
        'radius',100, ...
        'sensorRange',300, ...
        'vmax',10)];
end

end